### ISSUE TITLE
Add unit movement to board

### ISSUE THREAD

**Issue by MrGeektron** [BrosinTimeCode/RTS#5]

**Comment by Nurdoidz** [comment]
For basic unit movement, we likely need a real-time game loop. We could introduce ticks, which cycles through methods _x_ amount of times per second. One method of the loop checks the location of a unit and displays it on the board. Since unit locations would obviously be stored and calculated server-side, we need to introduce simple path finding as well. The client will then submit move orders (perhaps in `action unitID x y` format, i.e. `move 46 2 7` to move 46 to 2, 7).

- [ ] Add real-time game loop
- [ ] Add basic path finder
- [ ] Add a method to update the board display in the game loop
- [ ] Add player input command to move a unit #8 

Thoughts?

**Comment by MrGeektron** [comment]
All that seems good. 

 Add real-time game loop
- add in controller class/package
 Add basic path finder
- add in model class/package (we need to create a game model)
 Add a method to update the board display in the game loop
- add in controller class/package
 Add player input command to move a unit Add player input commands 
#8

**Comment by Nurdoidz** [comment]
As of #31, basic unit movement has been added and this issue should be considered resolved. Any additional unit movement functionality or unintended behavior should be opened as a new issue.
